import { Router } from 'express';
import multer from 'multer';
import { z } from 'zod';
import { env } from '../../config/env.js';
import { db, findDriverByUser, findUser, id, timestamp } from '../../database/store.js';
import { asyncHandler, fail, ok, paginate } from '../../shared/core.js';
import { requireAuth, requireRole } from '../../middleware/auth.js';
import { validate } from '../../middleware/errors.js';
import { storePrivateFile, validateUpload } from '../../services/storage.js';
const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: env.uploadMaxBytes, files: 1 } });
const router = Router();
router.use(requireAuth, requireRole('driver'));
const driverOf = (req) => findDriverByUser(req.user.id);
router.get('/profile', (req, res) => ok(res, 'Driver profile', { user: req.user, driver: driverOf(req), vehicle: db.vehicles.find((v) => v.driverId === driverOf(req)?.id) || null }));
router.put('/profile', validate(z.object({ name: z.string().min(2).max(120).optional(), email: z.string().email().optional(), phone: z.string().min(7).max(30).optional(), vehiclePlateNumber: z.string().min(2).max(30).optional() })), (req, res) => { const user = findUser({ id: req.user.id }); Object.assign(user, req.body, { updatedAt: timestamp() }); return ok(res, 'Driver profile updated', { user }); });
router.post('/status', validate(z.object({ isOnline: z.boolean(), latitude: z.number().optional(), longitude: z.number().optional() })), (req, res) => { const driver = driverOf(req); if (req.body.isOnline && (driver.status !== 'active' || driver.verificationStatus !== 'approved')) return fail(res, 403, 'Driver must be approved before going online', 'DRIVER_NOT_APPROVED'); driver.onlineStatus = req.body.isOnline; if (req.body.latitude !== undefined) driver.currentLocation = { latitude: req.body.latitude, longitude: req.body.longitude, recordedAt: timestamp() }; return ok(res, `Driver is now ${driver.onlineStatus ? 'online' : 'offline'}`, { driver }); });
router.post('/documents', upload.single('document'), validate(z.object({ documentType: z.string().min(2).max(60) })), asyncHandler(async (req, res) => { if (!req.file) return fail(res, 400, 'Document file is required', 'FILE_REQUIRED'); validateUpload(req.file); const documentId = id(); const stored = await storePrivateFile({ path: `drivers/${driverOf(req).id}/documents/${documentId}`, file: req.file }); const document = { id: documentId, driverId: driverOf(req).id, documentType: req.body.documentType, fileName: req.file.originalname, mimeType: req.file.mimetype, size: req.file.size, storage: stored, status: 'pending', createdAt: timestamp() }; db.documents.push(document); return ok(res, 'Document submitted for review', { document }, 201); }));
router.get('/verification-status', (req, res) => ok(res, 'Verification status', { status: driverOf(req).verificationStatus, documents: db.documents.filter((d) => d.driverId === driverOf(req).id).map(({ storage, ...d }) => d) }));
router.post('/identity-verification', validate(z.object({ verificationType: z.enum(['nin', 'biometric', 'facial']), providerReference: z.string().max(200).optional() })), (req, res) => { const driver = driverOf(req); driver.identityVerification = { ...req.body, status: 'pending_manual_review', submittedAt: timestamp() }; return ok(res, 'Identity verification submitted', { verification: driver.identityVerification }, 202); });
router.post('/location', validate(z.object({ latitude: z.number().gte(-90).lte(90), longitude: z.number().gte(-180).lte(180), rideId: z.string().optional() })), (req, res) => { const driver = driverOf(req); driver.currentLocation = { ...req.body, recordedAt: timestamp() }; if (req.body.rideId) db.rideLocations.push({ id: id(), driverId: driver.id, ...req.body, recordedAt: timestamp() }); return ok(res, 'Location updated', { location: driver.currentLocation }); });
router.get('/trips', (req, res) => ok(res, 'Driver trips', paginate(db.rides.filter((r) => r.driverId === driverOf(req).id), req.query.page, req.query.limit)));
router.get('/earnings', (req, res) => { const rides = db.rides.filter((r) => r.driverId === driverOf(req).id && r.status === 'completed'); return ok(res, 'Driver earnings', { total: rides.reduce((sum, r) => sum + Number(r.fare || 0), 0), trips: rides.length }); });
export default router;
